version: '3.4'

services:
  cars:
    image: ${DOCKER_REGISTRY-}cars
    build:
      context: .
      dockerfile: Cars/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:4001
    expose:
      - "4001"
    ports:
      - "4001:4001"
    networks:
      main:
        aliases:
          - cars

  users:
    image: ${DOCKER_REGISTRY-}users
    build:
      context: .
      dockerfile: Users/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:4002
    expose:
      - "4002"
    ports:
      - "4002:4002"
    networks:
      main:
        aliases:
          - users
  
networks:
  main: